### ISSUE TITLE
paper suggestion: Reconciling modern machine learning practiceand the bias-variance trade-off

### ISSUE THREAD

**Issue by seshkumar** [ImperialCollegeLondon/csml-reading-group#2]
Reconciling modern machine learning practice and the bias-variance trade-off
Mikhail Belkin, Daniel Hsu, Siyuan Ma, Soumik Mandal

https://arxiv.org/abs/1812.11118

**Comment by flaxter** [comment]
As a follow-up we might want to read: https://arxiv.org/abs/1903.07571

**Comment by seshkumar** [comment]
A more basic one is this one. May be the first in this line of research

https://arxiv.org/abs/1903.08560

Surprises in High-Dimensional Ridgeless Least Squares Interpolation
Trevor Hastie, Andrea Montanari, Saharon Rosset, Ryan J. Tibshirani

**Comment by seshkumar** [comment]
More references on double descent

- The generalization error of random features regression: Precise asymptotics and double descent curve. Song Mei, Andrea Montanari. https://arxiv.org/pdf/1908.05355

- Generalization of Two-layer Neural Networks: An Asymptotic Viewpoint  (ICLR 2020 under review)
https://openreview.net/forum?id=H1gBsgBYwH

- Deep Double Descent: Where Bigger Models and More Data Hurt (ICLR 2020 under review)
https://openreview.net/forum?id=B1g5sA4twr

**Comment by hsmathang** [comment]
I'm so interested on Double Descent. Can you reproducing DD on home?  I'm trying so hard, but idk how plot this. Some advice?
